In [1]:
# on peut avoir des liste de plusieurs liste en python du coup il ne distingue pas les  operations mathematiques

prix_liste = [100, 200, 300, 400]
print(prix_liste * 2)

[100, 200, 300, 400, 100, 200, 300, 400]

In [2]:
# avec numphy cest different car il travaille sur des nombres 

import numpy as np

prix_array = np.array([100, 200, 300, 400])
print(prix_array * 2)

[200 400 600 800]

In [3]:
print(prix_array.sum())
print(prix_array.mean())

1000
250.0

In [4]:
import time

grande_liste = list(range(1_000_000))
grand_array = np.array(grande_liste)

debut = time.time()
resultat_liste = [x * 2 for x in grande_liste]
print("Liste Python :", time.time() - debut, "secondes")

debut = time.time()
resultat_array = grand_array * 2
print("NumPy :", time.time() - debut, "secondes")

Liste Python : 0.17467164993286133 secondes
NumPy : 0.009839057922363281 secondes

In [5]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
# renvoie un tuple ,nombre de ligne , nombre de colones
print(df.shape)

(9994, 21)

In [8]:
# donne le type de chaque colones et verifie si les valeur son null
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [9]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [10]:
print(df["Profit"])

0        41.9136
1       219.5820
2         6.8714
3      -383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [11]:
ventes_a_perte = df[df["Profit"] < 0]
print(ventes_a_perte.shape)

(1871, 21)

In [12]:
print(df["Category"].unique())

<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [13]:
ventes_par_categorie = df.groupby("Category")["Sales"].sum()
print(ventes_par_categorie)

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [14]:
top5 = df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(5)
print(top5)

Sub-Category
Phones     330007.054
Chairs     328449.103
Storage    223843.608
Tables     206965.532
Binders    203412.733
Name: Sales, dtype: float64

In [15]:
print(df.isna().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [16]:
managers = pd.DataFrame({
    "Region": ["West", "East", "Central", "South"],
    "Manager": ["Sadie", "Chuck", "Kelly", "Cassandra"]
})
print(managers)

    Region    Manager
0     West      Sadie
1     East      Chuck
2  Central      Kelly
3    South  Cassandra

In [17]:
# fusion 
df_avec_manager = df.merge(managers, on="Region")
print(df_avec_manager.shape)
print(df_avec_manager[["Region", "Manager", "Sales"]].head())

(9994, 22)
  Region    Manager     Sales
0  South  Cassandra  261.9600
1  South  Cassandra  731.9400
2   West      Sadie   14.6200
3  South  Cassandra  957.5775
4  South  Cassandra   22.3680

In [18]:
ventes_region = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)
print(ventes_region)

top10_produits = df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)
print(top10_produits)

profit_segment = df.groupby("Segment")["Profit"].sum().sort_values(ascending=False)
print(profit_segment)

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64
Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64
Segment
Consumer       134119.2092
Corporate       91979.1340
Home Office     60298.6785
Name: Profit, dtype: float64

In [19]:
# on creer de feuilles de calcul differentes contenents  les informations sur les ventes par region ,le top 10 des produits,profit par segment
with pd.ExcelWriter("rapport_ventes.xlsx") as writer:
    ventes_region.to_excel(writer, sheet_name="Ventes par region")
    top10_produits.to_excel(writer, sheet_name="Top 10 produits")
    profit_segment.to_excel(writer, sheet_name="Profit par segment")

print("Rapport Excel généré !")

Rapport Excel généré !

In [20]:
verification = pd.read_excel("rapport_ventes.xlsx", sheet_name="Top 10 produits")
print(verification)

                                        Product Name      Sales
0              Canon imageCLASS 2200 Advanced Copier  61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
2  Cisco TelePresence System EX90 Videoconferenci...  22638.480
3       HON 5400 Series Task Chairs for Big and Tall  21870.576
4         GBC DocuBind TL300 Electric Binding System  19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System  19024.500
6               Hewlett Packard LaserJet 3310 Copier  18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...  18374.895
8          GBC DocuBind P400 Electric Binding System  17965.068
9        High Speed Automatic Electric Letter Opener  17030.312

In [21]:
print("Nombre de lignes (ventes de produits) :", df.shape[0])
print("Nombre de commandes uniques :", df["Order ID"].nunique())
print("Nombre de clients uniques :", df["Customer Name"].nunique())

Nombre de lignes (ventes de produits) : 9994
Nombre de commandes uniques : 5009
Nombre de clients uniques : 793

In [22]:
# analyse de la rentabiliter par segment
clients_par_segment = df.groupby("Segment")["Customer Name"].nunique()
print(clients_par_segment)

profit_par_client = profit_segment / clients_par_segment
print(profit_par_client.sort_values(ascending=False))

Segment
Consumer       409
Corporate      236
Home Office    148
Name: Customer Name, dtype: int64
Segment
Home Office    407.423503
Corporate      389.742093
Consumer       327.919827
dtype: float64

In [23]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Mois"] = df["Order Date"].dt.month

ventes_mois = df.groupby("Mois")["Sales"].sum().sort_values(ascending=False)
print(ventes_mois)

commandes_mois = df.groupby("Mois")["Order ID"].nunique().sort_values(ascending=False)
print(commandes_mois)

Mois
11    352461.0710
12    325293.5035
9     307649.9457
3     205005.4888
10    200322.9847
8     159044.0630
5     155028.8117
6     152718.6793
7     147238.0970
4     137762.1286
1      94924.8356
2      59751.2514
Name: Sales, dtype: float64
Mois
11    753
12    702
9     688
10    417
5     369
6     364
3     354
4     343
8     341
7     338
1     178
2     162
Name: Order ID, dtype: int64